Upgrade pip using easy_install if pip is broken
python-pip on ubuntu 16.04 breaks with:
    AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Workaround: upgrade pip using easy_install